export {sessionCols};

const sessionCols=[
    { field: 'InstId', headerText: 'InstId', type: 'number', width: '20' },
    { headerText: 'Saddr', field: 'Saddr', type: 'Buffer' },
    { field: 'Sid', headerText: 'Sid', type: 'number' },
    { field: 'Serial', headerText: 'Serial', type: 'number' },
    { headerText: 'Audsid', field: 'Audsid', type: 'number' },
    { headerText: 'Paddr', field: 'Paddr', type: 'Buffer' },
    { headerText: 'User', field: 'User', type: 'number' },
    { headerText: 'Username', field: 'Username', type: 'string', width: '100' },
    { headerText: 'Command', field: 'Command', type: 'number' },
    { headerText: 'Ownerid', field: 'Ownerid', type: 'number' },
    { headerText: 'Taddr', field: 'Taddr', type: 'string', width: '100' },
    { headerText: 'Lockwait', field: 'Lockwait', type: 'string', width: '100' },
    { headerText: 'Status', field: 'Status', type: 'string', width: '100' },
    { headerText: 'Server', field: 'Server', type: 'string', width: '100' },
    { headerText: 'Schema', field: 'Schema', type: 'number' },
    { headerText: 'Schemaname', field: 'Schemaname', type: 'string', width: '100' },
    { headerText: 'Osuser', field: 'Osuser', type: 'string', width: '100' },
    { headerText: 'Process', field: 'Process', type: 'string', width: '100' },
    { headerText: 'Machine', field: 'Machine', type: 'string', width: '100' },
    { headerText: 'Port', field: 'Port', type: 'number' },
    { headerText: 'Terminal', field: 'Terminal', type: 'string', width: '100' },
    { headerText: 'Program', field: 'Program', type: 'string', width: '100' },
    { headerText: 'Type', field: 'Type', type: 'string', width: '100' },
    { headerText: 'SqlAddress', field: 'SqlAddress', type: 'Buffer' },
    { headerText: 'SqlHashValue', field: 'SqlHashValue', type: 'number' },
    { headerText: 'SqlId', field: 'SqlId', type: 'string', width: '100' },
    { headerText: 'SqlChildNumber', field: 'SqlChildNumber', type: 'number' },
    { headerText: 'SqlExecStart', field: 'SqlExecStart', type: 'Date' },
    { headerText: 'SqlExecId', field: 'SqlExecId', type: 'number' },
    { headerText: 'PrevSqlAddr', field: 'PrevSqlAddr', type: 'Buffer' },
    { headerText: 'PrevHashValue', field: 'PrevHashValue', type: 'number' },
    { headerText: 'PrevSqlId', field: 'PrevSqlId', type: 'string', width: '100' },
    { headerText: 'PrevChildNumber', field: 'PrevChildNumber', type: 'number' },
    { headerText: 'PrevExecStart', field: 'PrevExecStart', type: 'Date' },
    { headerText: 'PrevExecId', field: 'PrevExecId', type: 'number' },
    { headerText: 'PlsqlEntryObjectId', field: 'PlsqlEntryObjectId', type: 'number' },
    { headerText: 'PlsqlEntrySubprogramId', field: 'PlsqlEntrySubprogramId', type: 'number' },
    { headerText: 'PlsqlObjectId', field: 'PlsqlObjectId', type: 'number' },
    { headerText: 'PlsqlSubprogramId', field: 'PlsqlSubprogramId', type: 'number' },
    { headerText: 'Module', field: 'Module', type: 'string', width: '100' },
    { headerText: 'ModuleHash', field: 'ModuleHash', type: 'number' },
    { headerText: 'Action', field: 'Action', type: 'string', width: '100' },
    { headerText: 'ActionHash', field: 'ActionHash', type: 'number' },
    { headerText: 'ClientInfo', field: 'ClientInfo', type: 'string', width: '100' },
    { headerText: 'FixedTableSequence', field: 'FixedTableSequence', type: 'number' },
    { headerText: 'RowWaitObj', field: 'RowWaitObj', type: 'number' },
    { headerText: 'RowWaitFile', field: 'RowWaitFile', type: 'number' },
    { headerText: 'RowWaitBlock', field: 'RowWaitBlock', type: 'number' },
    { headerText: 'RowWaitRow', field: 'RowWaitRow', type: 'number' },
    { headerText: 'TopLevelCall', field: 'TopLevelCall', type: 'number' },
    { headerText: 'LogonTime', field: 'LogonTime', type: 'Date' },
    { headerText: 'LastCallEt', field: 'LastCallEt', type: 'number' },
    { headerText: 'PdmlEnabled', field: 'PdmlEnabled', type: 'string', width: '100' },
    { headerText: 'FailoverType', field: 'FailoverType', type: 'string', width: '100' },
    { headerText: 'FailoverMethod', field: 'FailoverMethod', type: 'string', width: '100' },
    { headerText: 'FailedOver', field: 'FailedOver', type: 'string', width: '100' },
    { headerText: 'ResourceConsumerGroup', field: 'ResourceConsumerGroup', type: 'string',width: '100' },
    { headerText: 'PdmlStatus', field: 'PdmlStatus', type: 'string', width: '100' },
    { headerText: 'PddlStatus', field: 'PddlStatus', type: 'string', width: '100' },
    { headerText: 'PqStatus', field: 'PqStatus', type: 'string', width: '100' },
    { headerText: 'CurrentQueueDuration', field: 'CurrentQueueDuration', type: 'number' },
    { headerText: 'ClientIdentifier', field: 'ClientIdentifier', type: 'string', width: '100' },
    { headerText: 'BlockingSessionStatus', field: 'BlockingSessionStatus', type: 'string',width: '100' },
    { headerText: 'BlockingInstance', field: 'BlockingInstance', type: 'number' },
    { headerText: 'BlockingSession', field: 'BlockingSession', type: 'number' },
    { headerText: 'FinalBlockingSessionStatus', field: 'FinalBlockingSessionStatus',type: 'string', width: '100' },
    { headerText: 'FinalBlockingInstance', field: 'FinalBlockingInstance', type: 'number' },
    { headerText: 'FinalBlockingSession', field: 'FinalBlockingSession', type: 'number' },
    { headerText: 'Seq', field: 'Seq', type: 'number' },
    { headerText: 'EventN', field: 'EventN', type: 'number' },
    { headerText: 'Event', field: 'Event', type: 'string', width: '100' },
    { headerText: 'P1Text', field: 'P1Text', type: 'string', width: '100' },
    { headerText: 'P1', field: 'P1', type: 'number' },
    { headerText: 'P1Raw', field: 'P1Raw', type: 'Buffer' },
    { headerText: 'P2Text', field: 'P2Text', type: 'string', width: '100' },
    { headerText: 'P2', field: 'P2', type: 'number' },
    { headerText: 'P2Raw', field: 'P2Raw', type: 'Buffer' },
    { headerText: 'P3Text', field: 'P3Text', type: 'string', width: '100' },
    { headerText: 'P3', field: 'P3', type: 'number' },
    { headerText: 'P3Raw', field: 'P3Raw', type: 'Buffer' },
    { headerText: 'WaitClassId', field: 'WaitClassId', type: 'number' },
    { headerText: 'WaitClassN', field: 'WaitClassN', type: 'number' },
    { headerText: 'WaitClass', field: 'WaitClass', type: 'string', width: '100' },
    { headerText: 'WaitTime', field: 'WaitTime', type: 'number' },
    { headerText: 'SecondsInWait', field: 'SecondsInWait', type: 'number' },
    { headerText: 'State', field: 'State', type: 'string', width: '100' },
    { headerText: 'WaitTimeMicro', field: 'WaitTimeMicro', type: 'number' },
    { headerText: 'TimeRemainingMicro', field: 'TimeRemainingMicro', type: 'number' },
    { headerText: 'TotalTimeWaitedMicro', field: 'TotalTimeWaitedMicro', type: 'number' },
    { headerText: 'HeurTimeWaitedMicro', field: 'HeurTimeWaitedMicro', type: 'number' },
    { headerText: 'TimeSinceLastWaitMicro', field: 'TimeSinceLastWaitMicro', type: 'number' },
    { headerText: 'ServiceName', field: 'ServiceName', type: 'string', width: '100' },
    { headerText: 'SqlTrace', field: 'SqlTrace', type: 'string', width: '100' },
    { headerText: 'SqlTraceWaits', field: 'SqlTraceWaits', type: 'string', width: '100' },
    { headerText: 'SqlTraceBinds', field: 'SqlTraceBinds', type: 'string', width: '100' },
    { headerText: 'SqlTracePlanStats', field: 'SqlTracePlanStats', type: 'string', width: '100' },
    { headerText: 'SessionEditionId', field: 'SessionEditionId', type: 'number' },
    { headerText: 'CreatorAddr', field: 'CreatorAddr', type: 'Buffer' },
    { headerText: 'CreatorSerial', field: 'CreatorSerial', type: 'number' },
    { headerText: 'Ecid', field: 'Ecid', type: 'string', width: '100' },
    { headerText: 'SqlTranslationProfileId', field: 'SqlTranslationProfileId', type: 'number' },
    { headerText: 'PgaTunableMem', field: 'PgaTunableMem', type: 'number' },
    { headerText: 'ShardDdlStatus', field: 'ShardDdlStatus', type: 'string', width: '100' },
    { headerText: 'ConId', field: 'ConId', type: 'number' },
    { headerText: 'ExternalName', field: 'ExternalName', type: 'string', width: '100' },
    { headerText: 'PlsqlDebuggerConnected', field: 'PlsqlDebuggerConnected', type: 'string', width: '100' }

]
